### Create new account
POST {{base}}/wallbler/account
Content-Type: application/json
Accept: application/json

{
  "config.name": "test facebook account",
  "config.oAuthAccessToken": "EAApiYthtIG8BAA9tsFS3zXZCiX9fixZCCbr9wyrJujZBkbrIq8AZAI3VCzMVlSvdhoMemsuFnNNrFG7isCmVZBEI4nipZBKY11XaeJTYl9ReT7kiKxRzmpZBqTZBZASH5aaJTGu01tjjXMhQ9oG1PY2xqRfXUZCTudTFRSaA7o5Pk2wQZDZD",
  "config.enabled": false,
  "config.valid": false,
  "config.groupId": "111349400493820",
  "service.factoryPid": "com.nkoad.wallbler.core.implementation.facebook.FacebookAccount"
}

> {% client.global.set("account_pid", response.body['service.pid']); %}


### Update account
PUT {{base}}/wallbler/account/{{account_pid}}
Content-Type: application/json
Accept: application/json

{
  "config.name": "test facebook account changed",
  "config.oAuthAccessToken": "EAApiYthtIG8BAA9tsFS3zXZCiX9fixZCCbr9wyrJujZBkbrIq8AZAI3VCzMVlSvdhoMemsuFnNNrFG7isCmVZBEI4nipZBKY11XaeJTYl9ReT7kiKxRzmpZBqTZBZASH5aaJTGu01tjjXMhQ9oG1PY2xqRfXUZCTudTFRSaA7o5Pk2wQZDZD",
  "config.valid": true,
  "config.enabled": true,
  "config.groupId": "111349400493820"
}


### Get a single account
GET {{base}}/wallbler/account/{{account_pid}}
Accept: application/json


### Create new feed
POST {{base}}/wallbler/feed
Content-Type: application/json
Accept: application/json

{
  "config.name": "test facebook feed",
  "config.accountName": "test facebook account",
  "config.enabled": false,
  "config.delay": 12,
  "config.acceptedByDefault": false,
  "service.factoryPid": "com.nkoad.wallbler.core.implementation.facebook.FacebookFeed"
}

> {% client.global.set("feed_pid", response.body['service.pid']); %}


### Update feed
PUT {{base}}/wallbler/feed/{{feed_pid}}
Content-Type: application/json
Accept: application/json

{
  "config.name": "test facebook feed changed",
  "config.accountName": "test facebook account",
  "config.enabled": true,
  "config.delay": 24,
  "config.acceptedByDefault": true
}


### Get a single feed
GET {{base}}/wallbler/feed/{{feed_pid}}
Accept: application/json


### Get all feeds from account
GET {{base}}/wallbler/account/{{account_pid}}/
Accept: application/json


### Delete feed
DELETE {{base}}/wallbler/feed/{{feed_pid}}

> {% client.global.clear("feed_pid"); %}


### Delete account
DELETE {{base}}/wallbler/account/{{account_pid}}

> {% client.global.clear("account_pid"); %}

###

