### Create new account
POST {{base}}/wallbler/account
Content-Type: application/json
Accept: application/json

{
  "config.name": "test instagram account",
  "config.accessToken": "IGQVJVOHN4SjJISms0WWdGcmN2UUlsUER5VlEwRmJXbHJjOXhBclJvaU5MdzBsNWE3eFRNUDBRYk9oeVphamtMbDcwMXhGOHF0OFg2OXNadldOZAFZAJVHVJRDN3OEpDUWNyelZA6eWpn",
  "config.enabled": false,
  "config.valid": false,
  "config.refresh": 0,
  "service.factoryPid": "com.nkoad.wallbler.core.implementation.instagram.InstagramAccount"
}

> {% client.global.set("account_pid", response.body['service.pid']); %}


### Get a single account
GET {{base}}/wallbler/account/{{account_pid}}
Accept: application/json


### Get all feeds from account
GET {{base}}/wallbler/account/{{account_pid}}/
Accept: application/json


### Update account
PUT {{base}}/wallbler/account/{{account_pid}}
Content-Type: application/json
Accept: application/json

{
  "config.name": "test instagram account",
  "config.accessToken": "IGQVJVOHN4SjJISms0WWdGcmN2UUlsUER5VlEwRmJXbHJjOXhBclJvaU5MdzBsNWE3eFRNUDBRYk9oeVphamtMbDcwMXhGOHF0OFg2OXNadldOZAFZAJVHVJRDN3OEpDUWNyelZA6eWpn",
  "config.enabled": true,
  "config.valid": true,
  "config.refresh": 0
}


### Delete account
DELETE {{base}}/wallbler/account/{{account_pid}}

> {% client.global.clear("account_pid"); %}

###

